
---
- name: "[MAJ EMAIL]"
  hosts: [MAIL]
  tasks:

    - name: remettre en prod l'ancienne version de  configuration de redis
      shell: cd /home/dqe/email/conf && cp -pr ServerDQE_Tornado.cfg.new ServerDQE_Tornado.cfg


#    - name: Reboot service
#      shell: cd /var/dqe/scripts/ && ./restart_srv_email.sh
