---
- name: creation user
  hosts: [HOST]
  become: yes
  vars:
    name: nom_du_user
    group: groupe_du_user
    alias:  alias_du_user
  tasks:

  - name: Create user
    ansible.builtin.user:
      name: "{{name}}"
      group: "{{group}}"
      shell: /bin/bash
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/id_rsa

  - name: Allow "{{alias}}"  to have passwordless sudo
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^%{{alias}}'
      line: '{{alias}} ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'

